export const MAPVIEW_ACTIVITIES = 'MAPVIEW_ACTIVITIES';
export const MAPVIEW_CARDS = 'MAPVIEW_CARDS';
export const MAPVIEW_ALL = 'MAPVIEW_ALL';
export const MAPVIEW_PROMOTIONS = 'MAPVIEW_PROMOTIONS';
export const MAPVIEW_ITEMS = 'MAPVIEW_ITEMS';

export const DATA_MENU_HOME = 'DATA_MENU_HOME';
export const CHECK_LANGUAGE = 'CHECK_LANGUAGE';
export const CHECK_AUTH = 'CHECK_AUTH';
export const USER_PROFILE = 'USER_PROFILE';
export const DATA_USER = 'DATA_USER';
export const FB_TOKEN = 'FB_TOKEN';
export const LOADING_STATE = 'LOADING_STATE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const BACKGROUND_ACTIVITY = 'BACKGROUND_ACTIVITY';
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
export const ACTIVITY_CREATE = 'ACTIVITY_CREATE';
export const ACTIVITY_SHOW = 'ACTIVITY_SHOW';
export const FEED_DATA_ACTIVITY = 'FEED_DATA_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const DIFF_TIME = 'DIFF_TIME';
export const CHECK_DATA_ACTIVITY = 'CHECK_DATA_ACTIVITY';